-- SkyGrid Solar AI Supabase schema
-- Safe first step: create storage tables only. The production Streamlit app
-- continues to use Google Sheets until the collector is explicitly changed.

create table if not exists public.plant_capacity_history (
    id bigint generated by default as identity primary key,
    valid_from timestamptz not null,
    capacity_mw numeric(10, 3) not null check (capacity_mw > 0),
    comment text,
    created_at timestamptz not null default now(),
    unique (valid_from)
);

create table if not exists public.solar_measurements (
    time timestamptz primary key,
    fact_mw numeric(10, 3) not null check (fact_mw >= 0),
    source text not null default 'email',
    source_file text,
    loaded_at timestamptz not null default now()
);

create table if not exists public.weather_forecasts (
    time timestamptz not null,
    provider text not null default 'visual_crossing',
    rad numeric(10, 3) not null default 0,
    cloudcover numeric(6, 2) not null default 0,
    temp numeric(6, 2) not null default 0,
    windspeed numeric(6, 2) not null default 0,
    precipprob numeric(6, 2) not null default 0,
    loaded_at timestamptz not null default now(),
    primary key (time, provider, loaded_at)
);

create table if not exists public.generation_forecasts (
    id bigint generated by default as identity primary key,
    target_time timestamptz not null,
    forecast_mw numeric(10, 3) not null default 0,
    ai_forecast_mw numeric(10, 3) not null default 0,
    capacity_mw numeric(10, 3) not null,
    model_version text not null default 'collector-hist-gradient-error-v1',
    forecast_run_at timestamptz not null default now(),
    source text not null default 'collector',
    unique (target_time, model_version, forecast_run_at)
);

create table if not exists public.forecast_quality_daily (
    date date primary key,
    fact_mwh numeric(12, 3) not null default 0,
    base_mwh numeric(12, 3) not null default 0,
    ai_mwh numeric(12, 3) not null default 0,
    base_error_mwh numeric(12, 3) not null default 0,
    ai_error_mwh numeric(12, 3) not null default 0,
    base_mape_pct numeric(8, 2),
    ai_mape_pct numeric(8, 2),
    ai_improvement_pct numeric(8, 2),
    calculated_at timestamptz not null default now()
);

create index if not exists idx_solar_measurements_time
    on public.solar_measurements (time desc);

create index if not exists idx_weather_forecasts_time
    on public.weather_forecasts (time desc);

create index if not exists idx_generation_forecasts_target_time
    on public.generation_forecasts (target_time desc);

create index if not exists idx_generation_forecasts_run
    on public.generation_forecasts (forecast_run_at desc);

create index if not exists idx_capacity_history_valid_from
    on public.plant_capacity_history (valid_from desc);

alter table public.plant_capacity_history enable row level security;
alter table public.solar_measurements enable row level security;
alter table public.weather_forecasts enable row level security;
alter table public.generation_forecasts enable row level security;
alter table public.forecast_quality_daily enable row level security;

-- No anon/authenticated policies are created on purpose.
-- The collector and Streamlit server should use server-side secrets only.

