name: Keep Site Awake

on:
  schedule:
    - cron: '*/20 * * * *' # Запуск кожні 20 хвилин
  workflow_dispatch: # Можливість запустити вручну

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit
        run: |
          curl -I -L https://skygrid-ai.streamlit.app/
